# Trigger a build on version tags and push to nuget repository

trigger:
  tags:
    include:
      - 'v*'      
variables:
  - group: "Nuget Publish"
  - name: nugetApiKey
    value: $[variables.NUGET_API_KEY]

pr:
  branches:
    exclude:
      - '*'

    
jobs:
- job: buildMaster
  displayName: Build Master
  pool:
    vmImage: 'ubuntu-latest'

  steps:

  - task: Bash@3
    displayName: Set VERSION_TAG environment variable
    condition: startsWith(variables['build.sourceBranch'], 'refs/tags/v')
    inputs:
     targetType: inline
     script: |
       VERSION_TAG=`git describe --tags` && echo "##vso[task.setvariable variable=VERSION_TAG]$VERSION_TAG"
      
  - task: Assembly-Info-NetFramework@3
    displayName: Patch Assembly Version
    condition: startsWith(variables['build.sourceBranch'], 'refs/tags/v')
    inputs:
      Path: '$(Build.SourcesDirectory)'
      FileNames: |        
        **/AssemblyInfo.cs        
      InsertAttributes: false
      FileEncoding: 'auto'
      WriteBOM: false
      VersionNumber: '$(VERSION_TAG)'
      FileVersionNumber: '$(VERSION_TAG)'      
      LogLevel: 'verbose'
      FailOnWarning: true
      DisableTelemetry: true

  - task: Bash@3
    displayName: 'Build Solution'
    inputs:
      filePath: 'build.sh'
      arguments: '--target Build --configuration Release'

  - task: Bash@3
    displayName: 'Build Nuget Package'
    inputs:
      filePath: 'build.sh'
      arguments: '--target Pack-Release --configuration Release'

  - task: Bash@3
    displayName: 'Publish Nuget Package'
    inputs:
      filePath: 'build.sh'
      arguments: '--target Nuget-Push --configuration Release'
    env:
      NUGET_API_KEY: $(nugetApiKey)
      
  - publish: $(System.DefaultWorkingDirectory)/artifacts
    artifact: Shelly.Net
